import * as db from './db'
import { COLLECTIONS } from './db'
import { NOTIF_TYPE } from '../utils/constants'
import { uid } from '../utils/helpers'
import { nowISO } from '../utils/dates'

/**
 * Notification centre.
 *
 * Notifications are generated by the domain services (borrow, return, overdue
 * sweep, maintenance), never by components. Each one carries a `dedupeKey` so a
 * repeated sweep — the overdue check runs whenever staff open the app — reuses
 * the existing record instead of stacking duplicates.
 *
 * `userId` addresses the notification: a uid for one person, `null` for a
 * laboratory-wide alert. Reads are scoped in the data layer, so a student
 * receives their own plus the broadcasts, and never another student's.
 */

/**
 * @param {object} input
 * @param {string} input.type      one of NOTIF_TYPE
 * @param {string} input.title
 * @param {string} input.message
 * @param {string} [input.dedupeKey] stable key; a repeat is skipped
 * @param {string} [input.toolId]
 * @param {string} [input.userId]  recipient, or null for everyone
 */
export async function create(input) {
  if (input.dedupeKey) {
    const existing = await findByDedupeKey(input.dedupeKey)
    if (existing) return existing
  }
  const record = {
    id: uid('NOTIF'),
    type: input.type ?? NOTIF_TYPE.SYSTEM,
    title: input.title ?? 'Notification',
    message: input.message ?? '',
    toolId: input.toolId ?? null,
    toolName: input.toolName ?? null,
    userId: input.userId ?? null,
    userName: input.userName ?? null,
    transactionId: input.transactionId ?? null,
    link: input.link ?? null,
    dedupeKey: input.dedupeKey ?? null,
    read: input.read ?? false,
    createdAt: input.createdAt ?? nowISO(),
  }
  await db.insert(COLLECTIONS.notifications, record)
  return record
}

export async function createMany(inputs) {
  const created = []
  for (const input of inputs) created.push(await create(input))
  return created
}

async function findByDedupeKey(key) {
  const rows = await db.query(COLLECTIONS.notifications, (n) => n.dedupeKey === key)
  return rows[0] ?? null
}

const byNewest = (a, b) => new Date(b.createdAt) - new Date(a.createdAt)

export async function listAll() {
  // Copied before sorting: the array from `db.list()` is the live cache.
  return [...(await db.list(COLLECTIONS.notifications))].sort(byNewest)
}

/**
 * Notifications visible to one user.
 *
 * The query itself is already restricted by role — staff stream the collection,
 * a student streams `userId == uid` plus the broadcasts — so this only re-checks
 * the ownership rule locally.
 */
export async function listFor(user, { seeAll = false } = {}) {
  const rows = await listAll()
  if (seeAll) return rows
  if (!user) return []
  return rows.filter((n) => !n.userId || n.userId === user.id)
}

export async function unreadCount(user, options) {
  return (await listFor(user, options)).filter((n) => !n.read).length
}

export async function markRead(id, read = true) {
  return db.update(COLLECTIONS.notifications, id, { read })
}

/**
 * Mark several as read, tolerating the ones the caller may not write.
 *
 * @returns {{ updated: number, skipped: number }}
 */
export async function markAllRead(ids) {
  let updated = 0
  let skipped = 0
  for (const id of ids) {
    try {
      await db.update(COLLECTIONS.notifications, id, { read: true })
      updated++
    } catch (err) {
      console.warn('[notifications] could not mark as read', id, err)
      skipped++
    }
  }
  return { updated, skipped, length: updated }
}

export async function remove(id) {
  return db.remove(COLLECTIONS.notifications, id)
}

/** Delete the read notifications the caller is allowed to delete. */
export async function removeRead(ids) {
  const rows = await db.query(
    COLLECTIONS.notifications,
    (n) => ids.includes(n.id) && n.read,
  )
  let removed = 0
  for (const row of rows) {
    try {
      await db.remove(COLLECTIONS.notifications, row.id)
      removed++
    } catch (err) {
      console.warn('[notifications] could not delete', row.id, err)
    }
  }
  return removed
}

export async function clearAll() {
  return db.clearCollection(COLLECTIONS.notifications)
}

export async function removeForTool(toolId) {
  return db.removeWhere(COLLECTIONS.notifications, (n) => n.toolId === toolId)
}

/* ------------------------------------------------------------------ *
 * Builders — one place per notification wording, so the copy in the
 * notification centre always matches the copy in a toast.
 * ------------------------------------------------------------------ */

export const templates = {
  overdue: (tool, txn, user) => ({
    type: NOTIF_TYPE.OVERDUE,
    title: 'Tool overdue',
    message: `${tool.name} has not been returned. Borrowed by ${user?.fullName ?? 'a user'}.`,
    dedupeKey: `overdue:${txn.id}`,
    toolId: tool.id,
    toolName: tool.name,
    userId: null,
    transactionId: txn.id,
    link: `/tools/${tool.id}`,
  }),

  dueSoon: (tool, txn, user) => ({
    type: NOTIF_TYPE.DUE_SOON,
    title: 'Tool due soon',
    message: `${tool.name} is due back on ${new Date(txn.dueDate).toLocaleDateString('en-US', {
      month: 'long',
      day: 'numeric',
    })}.`,
    dedupeKey: `due-soon:${txn.id}`,
    toolId: tool.id,
    toolName: tool.name,
    userId: user?.id ?? null,
    transactionId: txn.id,
    link: `/tools/${tool.id}`,
  }),

  borrowed: (tool, txn, user) => ({
    type: NOTIF_TYPE.BORROWED,
    title: 'Tool borrowed',
    message: `${tool.name} was issued to ${user?.fullName ?? 'a user'}.`,
    toolId: tool.id,
    toolName: tool.name,
    userId: null,
    transactionId: txn.id,
    link: `/tools/${tool.id}`,
  }),

  returned: (tool, txn, user) => ({
    type: NOTIF_TYPE.RETURNED,
    title: 'Tool returned',
    message: `${tool.name} was successfully returned by ${user?.fullName ?? 'a user'}.`,
    toolId: tool.id,
    toolName: tool.name,
    userId: null,
    transactionId: txn.id,
    link: `/tools/${tool.id}`,
  }),

  damaged: (tool, txn, user) => ({
    type: NOTIF_TYPE.DAMAGED,
    title: 'Damaged tool returned',
    message: `${tool.name} was returned in a damaged condition by ${
      user?.fullName ?? 'a user'
    }. It has been pulled from circulation.`,
    toolId: tool.id,
    toolName: tool.name,
    userId: null,
    transactionId: txn?.id ?? null,
    link: `/tools/${tool.id}`,
  }),

  maintenance: (tool, record) => ({
    type: NOTIF_TYPE.MAINTENANCE,
    title: 'Maintenance scheduled',
    message: `${tool.name} is scheduled for ${String(
      record?.type ?? 'maintenance',
    ).toLowerCase()} maintenance.`,
    dedupeKey: record?.id ? `maintenance:${record.id}` : null,
    toolId: tool.id,
    toolName: tool.name,
    link: `/tools/${tool.id}`,
  }),

  maintenanceDue: (tool) => ({
    type: NOTIF_TYPE.MAINTENANCE,
    title: 'Maintenance due',
    message: `${tool.name} has reached its scheduled maintenance date.`,
    dedupeKey: `maintenance-due:${tool.id}:${tool.nextMaintenanceDate ?? ''}`,
    toolId: tool.id,
    toolName: tool.name,
    link: `/tools/${tool.id}`,
  }),

  statusChanged: (tool, from, to) => ({
    type: NOTIF_TYPE.SYSTEM,
    title: 'Tool status updated',
    message: `${tool.name} changed from ${from} to ${to}.`,
    toolId: tool.id,
    toolName: tool.name,
    link: `/tools/${tool.id}`,
  }),
}
