-- Smart Tool Monitoring System — schema.
--
-- Derived from the application's own models: the records `src/services/*.js`
-- write through the `src/services/db.js` API, and nothing else. Seven tables,
-- one per entry in `COLLECTIONS`.
--
-- Two decisions shape everything below.
--
--  1. **Business ids stay text.** `TOOL-00001`, `TXN-20260611-DPJD16` and
--     `NOTIF-…` are generated by the application, printed on QR labels and
--     embedded in `tools.qr_code`. Re-keying to uuid would invalidate every
--     label, so the application's ids are the primary keys.
--
--  2. **`profiles.id` is the Supabase Auth uuid**, so `auth.uid()` can be used
--     directly in RLS. The application reads its profile by session id, which is
--     exactly what `db.getDirect('users', uid)` does at sign-in.
--
-- Columns are snake_case; the data layer converts to and from the camelCase the
-- application uses, so neither side has to bend to the other.
--
-- No rows are inserted anywhere in this file. The database is empty after it
-- runs, by design.

/* ------------------------------------------------------------------ *
 * profiles  (the application's `users` collection)
 *
 * Credentials are NOT here. Supabase Auth owns the password; this table owns
 * the role, the status and the directory details. There is deliberately no
 * password, hash, salt or username column — the sign-in identity is the email
 * on the Auth account.
 * ------------------------------------------------------------------ */
create table if not exists public.profiles (
  id              uuid primary key references auth.users(id) on delete cascade,
  email           text not null,
  first_name      text not null default '',
  last_name       text not null default '',
  full_name       text not null,
  display_name    text not null default '',
  role            text not null check (role in ('Admin', 'Instructor', 'Student')),
  status          text not null default 'Pending'
                  check (status in ('Active', 'Pending', 'Inactive', 'Suspended')),
  student_id      text not null default '',
  course          text not null default '',
  year_level      text not null default 'N/A',
  employee_id     text not null default '',
  department      text not null default '',
  contact         text not null default '',
  registered_self boolean not null default false,
  created_at      timestamptz not null default now(),
  created_by      uuid references public.profiles(id) on delete set null,
  updated_at      timestamptz not null default now(),
  last_login_at   timestamptz,
  approved_at     timestamptz,
  approved_by     uuid references public.profiles(id) on delete set null,

  -- Length caps, so a direct API call cannot store a megabyte in a name that
  -- every staff read then has to carry.
  constraint profiles_full_name_len   check (char_length(full_name)   between 1 and 120),
  constraint profiles_first_name_len  check (char_length(first_name)  <= 60),
  constraint profiles_last_name_len   check (char_length(last_name)   <= 60),
  constraint profiles_display_len     check (char_length(display_name)<= 120),
  constraint profiles_email_len       check (char_length(email)       <= 160),
  constraint profiles_student_id_len  check (char_length(student_id)  <= 40),
  constraint profiles_employee_id_len check (char_length(employee_id) <= 40),
  constraint profiles_department_len  check (char_length(department)  <= 120),
  constraint profiles_course_len      check (char_length(course)      <= 120),
  constraint profiles_year_level_len  check (char_length(year_level)  <= 40),
  constraint profiles_contact_len     check (char_length(contact)     <= 40)
);

create unique index if not exists profiles_email_key on public.profiles (lower(email));
create index if not exists profiles_role_idx   on public.profiles (role);
create index if not exists profiles_status_idx on public.profiles (status);

/* ------------------------------------------------------------------ *
 * tools
 * ------------------------------------------------------------------ */
create table if not exists public.tools (
  id                     text primary key,
  name                   text not null,
  category               text not null default '',
  description            text not null default '',
  brand                  text not null default '',
  model                  text not null default '',
  serial_number          text not null default '',
  qr_code                text not null default '',
  status                 text not null default 'Available'
                         check (status in ('Available','Borrowed','Overdue','Maintenance','Damaged','Lost','Retired')),
  condition              text not null default 'Good'
                         check (condition in ('Excellent','Good','Fair','Needs Repair','Damaged')),
  location               text not null default '',
  notes                  text not null default '',
  purchase_date          timestamptz,
  last_maintenance_date  timestamptz,
  next_maintenance_date  timestamptz,
  -- Denormalised pointers to the live loan, as the application maintains them.
  current_borrower_id    text,
  current_transaction_id text,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),

  constraint tools_name_len check (char_length(name) between 1 and 160)
);

create index if not exists tools_status_idx   on public.tools (status);
create index if not exists tools_category_idx on public.tools (category);
create index if not exists tools_borrower_idx on public.tools (current_borrower_id);

/* ------------------------------------------------------------------ *
 * transactions
 *
 * `user_id` is text, not a foreign key to `profiles`. The application stores
 * the borrower's id alongside a denormalised `user_name`, and a loan must
 * survive the account being deleted — the laboratory record is the point.
 * Deleting a profile therefore cannot silently delete history.
 * ------------------------------------------------------------------ */
create table if not exists public.transactions (
  id               text primary key,
  tool_id          text not null references public.tools(id) on delete restrict,
  tool_name        text not null default '',
  tool_category    text not null default '',
  user_id          text not null,
  user_name        text not null default '',
  user_role        text not null default '',
  borrow_date      timestamptz not null,
  due_date         timestamptz not null,
  return_date      timestamptz,
  status           text not null default 'Borrowed'
                   check (status in ('Borrowed','Returned','Overdue','Damaged','Lost')),
  condition_out    text not null default '',
  condition_in     text,
  purpose          text not null default '',
  notes            text not null default '',
  issued_by_id     text,
  issued_by_name   text,
  received_by_id   text,
  received_by_name text,
  was_overdue      boolean not null default false,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),

  constraint transactions_dates check (due_date >= borrow_date)
);

create index if not exists transactions_user_idx   on public.transactions (user_id);
create index if not exists transactions_tool_idx   on public.transactions (tool_id);
create index if not exists transactions_status_idx on public.transactions (status);
-- Backs the "is this tool already out?" lookup the borrow path performs.
create index if not exists transactions_active_idx on public.transactions (tool_id, status)
  where status in ('Borrowed', 'Overdue');

/* ------------------------------------------------------------------ *
 * maintenance
 * ------------------------------------------------------------------ */
create table if not exists public.maintenance (
  id              text primary key,
  tool_id         text not null references public.tools(id) on delete restrict,
  tool_name       text not null default '',
  type            text not null default '',
  technician      text not null default '',
  date            timestamptz not null,
  next_date       timestamptz,
  cost            numeric(12, 2) not null default 0 check (cost >= 0),
  notes           text not null default '',
  status          text not null default 'Scheduled'
                  check (status in ('Scheduled','In Progress','Completed','Cancelled')),
  completed_at    timestamptz,
  created_by_id   text,
  created_by_name text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index if not exists maintenance_tool_idx   on public.maintenance (tool_id);
create index if not exists maintenance_status_idx on public.maintenance (status);

/* ------------------------------------------------------------------ *
 * notifications
 *
 * `user_id` NULL means laboratory-wide: everyone signed in may read it.
 * ------------------------------------------------------------------ */
create table if not exists public.notifications (
  id             text primary key,
  type           text not null
                 check (type in ('overdue','due_soon','returned','borrowed','damaged','maintenance','system')),
  title          text not null,
  message        text not null default '',
  tool_id        text,
  tool_name      text,
  transaction_id text,
  user_id        text,
  user_name      text,
  read           boolean not null default false,
  link           text,
  dedupe_key     text,
  created_at     timestamptz not null default now(),

  constraint notifications_title_len   check (char_length(title)   <= 120),
  constraint notifications_message_len check (char_length(message) <= 500)
);

create index if not exists notifications_user_idx    on public.notifications (user_id);
create index if not exists notifications_created_idx on public.notifications (created_at desc);
-- The application's de-duplication key: at most one live notification per key.
create unique index if not exists notifications_dedupe_key on public.notifications (dedupe_key)
  where dedupe_key is not null;

/* ------------------------------------------------------------------ *
 * activity_logs  (the application's `activityLogs` collection)
 *
 * Append-only audit trail.
 * ------------------------------------------------------------------ */
create table if not exists public.activity_logs (
  id             text primary key,
  action         text not null,
  tool_id        text,
  tool_name      text,
  user_id        text not null,
  user_name      text not null default '',
  transaction_id text,
  message        text not null default '',
  meta           jsonb not null default '{}'::jsonb,
  created_at     timestamptz not null default now(),

  constraint activity_logs_message_len check (char_length(message) <= 500)
);

create index if not exists activity_logs_created_idx on public.activity_logs (created_at desc);
create index if not exists activity_logs_user_idx    on public.activity_logs (user_id);

/* ------------------------------------------------------------------ *
 * settings
 *
 * One row, as the application keeps one `settings/app-settings` record.
 * ------------------------------------------------------------------ */
create table if not exists public.settings (
  id                        text primary key default 'app-settings',
  lab_name                  text not null default '',
  lab_location              text not null default '',
  institution               text not null default '',
  theme                     text not null default 'light',
  default_borrow_days       integer not null default 3  check (default_borrow_days > 0),
  max_borrow_days           integer not null default 30 check (max_borrow_days > 0),
  due_soon_threshold_days   integer not null default 1  check (due_soon_threshold_days >= 0),
  maintenance_interval_days integer not null default 90 check (maintenance_interval_days > 0),
  notify_due_soon           boolean not null default true,
  notify_overdue            boolean not null default true,
  notify_returns            boolean not null default true,
  notify_maintenance        boolean not null default true,
  created_at                timestamptz not null default now(),
  updated_at                timestamptz not null default now(),

  constraint settings_single_row check (id = 'app-settings'),
  constraint settings_borrow_range check (max_borrow_days >= default_borrow_days)
);

/* ------------------------------------------------------------------ *
 * updated_at maintenance
 * ------------------------------------------------------------------ */
create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

do $$
declare t text;
begin
  foreach t in array array['profiles','tools','transactions','maintenance','settings'] loop
    execute format(
      'drop trigger if exists %I_touch on public.%I; ' ||
      'create trigger %I_touch before update on public.%I ' ||
      'for each row execute function public.touch_updated_at()',
      t, t, t, t);
  end loop;
end $$;
